# Generated by Django 5.2.17 on 2026-08-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Stamped automatically whenever verification_status changes (see signals.py). Used to enforce the 30-day reapply cooldown after rejection.', null=True),
        ),
    ]
