# Generated by Django 5.2.17 on 2026-08-10 16:38

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_status_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX, up to 10 MB.', null=True, upload_to='profiles/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.validators.validate_cv_file_size]),
        ),
    ]
