# Generated by Django 5.2.17 on 2026-08-11 19:53

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG or PNG, up to 5 MB.', null=True, upload_to='profiles/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), users.validators.validate_photo_size]),
        ),
    ]
