# Generated by Django 5.2.17 on 2026-09-02 18:19

import ajna_health_lens.validators
import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX, up to 10 MB.', null=True, upload_to='profiles/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.validators.validate_cv_file_size, ajna_health_lens.validators.validate_document_content]),
        ),
    ]
