# Generated by Django 5.2.17 on 2026-09-30 05:37

import ajna_health_lens.storage
import ajna_health_lens.validators
import django.core.validators
import users.validators
import shutil
from pathlib import Path

from django.db import migrations, models


def _move_files(model_label, field, source_setting, target_setting):
    """Moves already-uploaded files between the public MEDIA_ROOT and
    PRIVATE_MEDIA_ROOT (same relative name, so stored paths don't change).
    Skips anything missing or already moved, so it's safe to re-run."""
    def move(apps, schema_editor):
        from django.conf import settings

        model = apps.get_model(*model_label.split('.'))
        source, target = Path(getattr(settings, source_setting)), Path(getattr(settings, target_setting))
        for name in model.objects.exclude(**{field: ''}).exclude(**{f'{field}__isnull': True}).values_list(field, flat=True):
            old, new = source / name, target / name
            if old.is_file() and not new.exists():
                new.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(old), str(new))
    return move


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF, DOC, or DOCX, up to 10 MB.', null=True, storage=ajna_health_lens.storage.private_storage, upload_to='profiles/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), users.validators.validate_cv_file_size, ajna_health_lens.validators.validate_document_content]),
        ),
        migrations.RunPython(
            _move_files('users.User', 'cv_file', 'MEDIA_ROOT', 'PRIVATE_MEDIA_ROOT'),
            _move_files('users.User', 'cv_file', 'PRIVATE_MEDIA_ROOT', 'MEDIA_ROOT'),
        ),
    ]
