# Generated by Django 5.2.17 on 2026-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_private_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
    ]
