# Generated by Django 5.2.17 on 2026-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verification_not_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the person proved they receive mail at this address (users/email_confirmation.py). Cleared whenever the email changes. Organization access by email domain needs it.', null=True),
        ),
    ]
