# Generated by Django 5.2.17 on 2026-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_email_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_renewal_reminders',
            field=models.BooleanField(default=True, help_text='Emails before a subscription ends (billing/reminders.py).', verbose_name='Subscription renewal reminders'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_topic_digest',
            field=models.BooleanField(default=True, help_text='The weekly email listing new articles in followed sections and topics.', verbose_name='Weekly digest of topics I follow'),
        ),
        migrations.AddField(
            model_name='user',
            name='erased_at',
            field=models.DateTimeField(blank=True, help_text="Set when the account was deleted at the person's request: personal data removed, row kept only so receipts and published records stay intact (users/privacy.py erase_user).", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the person agreed to the Terms of use and Privacy policy at sign-up.', null=True),
        ),
    ]
