# Generated by Django 5.2.17 on 2026-09-07 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_article_articles_ar_status_edb746_idx'),
        ('billing', '0002_planfeature_subscriptionplan_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='grants_ad_free_reading',
            field=models.BooleanField(default=True, help_text='Subscribers on this plan never see ads (billing.access/ads.services).'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grants_unlimited_articles',
            field=models.BooleanField(default=True, help_text='Subscribers on this plan bypass both the subscription-tier paywall and the metered free-sample limit entirely (billing.access.article_is_accessible).'),
        ),
        migrations.CreateModel(
            name='MeteredArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('period', models.CharField(help_text='Calendar-month bucket, e.g. "2026-09".', max_length=7)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metered_reads', to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metered_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'period'], name='billing_met_user_id_293df8_idx'), models.Index(fields=['session_key', 'period'], name='billing_met_session_42a73e_idx')],
            },
        ),
    ]
