# Generated by Django 5.2.17 on 2026-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionplan_grants_ad_free_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='grants_premium_newsletter',
            field=models.BooleanField(default=False, help_text='Subscribers on this plan receive newsletter issues sent to "Premium subscribers only" (newsletter.recipients.confirmed_recipients), in addition to every regular issue.'),
        ),
    ]
