# Generated by Django 5.2.17 on 2026-09-08 11:26

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_keywordfollow'),
        ('billing', '0004_subscriptionplan_grants_premium_newsletter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='gift_articles_per_month',
            field=models.PositiveIntegerField(default=0, help_text='How many distinct subscription-tier articles a subscriber on this plan can gift to non-subscribers each month, via a shareable link (billing.access.create_or_get_article_gift). 0 disables gifting for this plan.'),
        ),
        migrations.CreateModel(
            name='ArticleGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=billing.models.generate_gift_token, max_length=64, unique=True)),
                ('period', models.CharField(help_text='Calendar-month bucket, e.g. "2026-09".', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_links', to='articles.article')),
                ('gifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_gifts_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('gifter', 'article', 'period')},
            },
        ),
    ]
