# Generated by Django 5.2.17 on 2026-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptionplan_gift_articles_per_month_articlegift'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='grants_full_archive',
            field=models.BooleanField(default=False, help_text='Subscribers on this plan can read archived (Article.Status.ARCHIVED) articles in full, regardless of the access tier those articles had while still active.'),
        ),
    ]
