# Generated by Django 5.2.17 on 2026-09-29 03:35

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_publish_permission'),
        ('billing', '0006_subscriptionplan_grants_full_archive'),
        ('training', '0004_course_catalog_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('subscription', 'Subscription'), ('article', 'Article purchase'), ('course', 'Training course')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('gateway', models.CharField(default='fonepay', max_length=20)),
                ('reference', models.CharField(default=billing.models.generate_payment_reference, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for payment'), ('success', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('qr_message', models.TextField(blank=True, help_text='Fonepay QR payload, shown as a QR or passed to a bank app.')),
                ('websocket_url', models.CharField(blank=True, max_length=500)),
                ('gateway_trace_id', models.CharField(blank=True, max_length=64)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Last status response from the gateway.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='articles.article')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='training.trainingcourse')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='billing_pay_status_f64990_idx')],
            },
        ),
    ]
