# Generated by Django 5.2.17 on 2026-10-05 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.conf import settings as django_settings
from django.db import migrations, models


def backfill_existing_payments(apps, schema_editor):
    """Payments made before VAT was added: the whole amount was the price.
    Paid ones get receipt numbers in the order they were paid."""
    Payment = apps.get_model('billing', 'Payment')
    ReceiptSequence = apps.get_model('billing', 'ReceiptSequence')
    for payment in Payment.objects.filter(subtotal=0).exclude(amount=0):
        payment.subtotal = payment.amount
        payment.save(update_fields=['subtotal'])
    sequence, _ = ReceiptSequence.objects.get_or_create(name='receipts')
    for payment in Payment.objects.filter(status='success', receipt_number__isnull=True).order_by('completed_at', 'pk'):
        sequence.last_number += 1
        payment.receipt_number = f'{django_settings.RECEIPT_PREFIX}{sequence.last_number:06d}'
        payment.save(update_fields=['receipt_number'])
    sequence.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_verify_pending_payments_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who recorded a manual payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='return_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price before VAT.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total paid, VAT included.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('fonepay', 'Fonepay'), ('manual', 'Recorded by staff'), ('stub', 'Test gateway')], default='fonepay', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('article', 'Article purchase'), ('course', 'Training course'), ('institutional', 'Institutional subscription')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_domains', models.TextField(help_text='One per line, e.g. nhrc.gov.np. Addresses at subdomains (staff@dept.nhrc.gov.np) count too. Public email providers (gmail.com and the like) are refused.')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('seats', models.PositiveIntegerField(blank=True, help_text='Most people who can join. Leave empty for no limit.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop access straight away.')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Gets the receipt for payments recorded against this organization.', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Staff only — contract details, invoice numbers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='Decides what members get (ad-free, archive, gifting…).', on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='billing.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.RunPython(backfill_existing_payments, migrations.RunPython.noop),
    ]
