# Generated by Django 5.2.17 on 2026-10-05 10:50

from django.db import migrations, models


def backfill(apps, schema_editor):
    Payment = apps.get_model('billing', 'Payment')
    for payment in Payment.objects.filter(billed_name='').exclude(receipt_number=None).select_related('user', 'organization'):
        if payment.organization_id:
            payment.billed_name, payment.billed_email = payment.organization.name, payment.organization.contact_email
        elif payment.user_id:
            name = f'{payment.user.first_name} {payment.user.last_name}'.strip()
            payment.billed_name, payment.billed_email = name or payment.user.email, payment.user.email
        payment.save(update_fields=['billed_name', 'billed_email'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_payment_refunds_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billed_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='billed_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
