# Generated by Django 5.2.17 on 2026-10-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_payment_billed_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
