# Generated by Django 5.2.17 on 2026-10-05 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_payment_refund_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pan',
            field=models.CharField(blank=True, help_text='Printed on their tax invoices (9 digits).', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'A PAN is 9 digits.')], verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_pan',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'A PAN is 9 digits.')], verbose_name='Buyer PAN'),
        ),
    ]
