# Generated by Django 5.2.17 on 2026-10-05 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_search_text_word_index'),
        ('billing', '0014_buyer_pan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_manager',
            field=models.ForeignKey(blank=True, help_text='The staff member this organization deals with — shown on their dashboard and in reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_on', models.DateField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.article')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='billing.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'read_on'], name='billing_org_organiz_5844aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'article', 'read_on'), name='one_read_per_member_article_day')],
            },
        ),
    ]
