# Generated by Django 5.2.17 on 2026-10-06 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_organization_report_schedules'),
        ('training', '0004_course_catalog_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount, before VAT.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price before any discount, before VAT. Empty when no code was used.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='A free trial from a code (billing/promotions.py).'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What readers type. Stored in capitals; typing is case-insensitive.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9-]{2,39}$', 'Letters, digits and hyphens (3–40), e.g. LAUNCH50.')])),
                ('kind', models.CharField(choices=[('launch', 'Launch offer'), ('student', 'Student pricing'), ('partner', 'Partner deal'), ('trial', 'Free trial'), ('other', 'Other')], default='launch', max_length=20)),
                ('campaign', models.CharField(blank=True, help_text='Groups codes in reports, e.g. "Launch 2026".', max_length=100)),
                ('partner_name', models.CharField(blank=True, help_text='For partner deals: who it was made for.', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Shown to the reader when the code is applied, e.g. "Launch offer — 50% off".', max_length=200)),
                ('percent_off', models.PositiveSmallIntegerField(blank=True, help_text='e.g. 50 for half price. 100 = free.', null=True)),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, help_text='Rupees off the price before VAT.', max_digits=10, null=True)),
                ('trial_days', models.PositiveSmallIntegerField(blank=True, help_text='Free days of the trial plan, no payment.', null=True)),
                ('applies_to_subscriptions', models.BooleanField(default=True)),
                ('applies_to_articles', models.BooleanField(default=False, verbose_name='Applies to special articles')),
                ('applies_to_courses', models.BooleanField(default=False, verbose_name='Applies to training courses')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Last day it can be used.', null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total uses. Empty = no limit.', null=True)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1, help_text='Uses per person.')),
                ('new_subscribers_only', models.BooleanField(default=False, help_text='Only for people who have never had a subscription.')),
                ('email_domains', models.TextField(blank=True, help_text="Only for confirmed email addresses at these domains (one per line, subdomains count) — e.g. edu.np for students, or a partner's domain. Empty = anyone.")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Only these courses (none = every course).', related_name='promo_codes', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, help_text='Only these plans (none = every plan).', related_name='promo_codes', to='billing.subscriptionplan')),
                ('trial_plan', models.ForeignKey(blank=True, help_text='The plan the trial gives access to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial_codes', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.promocode'),
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='What it was used on.', max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Before VAT.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.promocode')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemption', to='billing.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'user'], name='billing_pro_code_id_58feee_idx')],
            },
        ),
    ]
