# Generated by Django 5.2.17 on 2026-08-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Author ordering on the article byline.')),
                ('is_corresponding', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('article_type', models.CharField(choices=[('original_research', 'Original Research'), ('review_article', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('methodology_paper', 'Methodology Paper'), ('editorial', 'Editorial'), ('news_commentary', 'News & Commentary'), ('letter_to_editor', 'Letter to Editor')], max_length=30)),
                ('access_type', models.CharField(choices=[('open_access', 'Open Access'), ('subscription', 'Subscription')], help_text='Defaults from article_type on creation; editors may override.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles/%Y/%m/')),
                ('html_content', models.TextField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=10, null=True)),
                ('page_numbers', models.CharField(blank=True, max_length=20, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issues.issue')),
            ],
        ),
    ]
