# Generated by Django 5.2.17 on 2026-08-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submission',
            field=models.OneToOneField(blank=True, help_text='Source submission this article was promoted from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
