# Generated by Django 5.2.17 on 2026-08-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        # Originally also added Article.submission (a OneToOneField to the
        # since-removed submissions.Submission — see CLAUDE.md's SCOPE NOTE)
        # here. Dropped from this historical migration entirely, not just
        # unapplied forward, because a field referencing a model that no
        # longer exists anywhere in the migration graph can't be resolved
        # when Django replays history from scratch (e.g. building a fresh
        # test database) — even though the field's own AddField/RemoveField
        # pair would otherwise cancel out at the current end state.
        migrations.AddField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
