# Generated by Django 5.2.17 on 2026-08-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, help_text='Bibliography, one formatted citation per line. Rendered as a numbered list.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, help_text='Full-text body HTML, rendered as-is (trusted — admin/editor-authored only, never end-user input). Shown only for open-access articles; subscription articles stay gated behind the Phase 6 paywall regardless of this field.', null=True),
        ),
    ]
