# Generated by Django 5.2.17 on 2026-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_references_alter_article_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='access_type',
            field=models.CharField(blank=True, choices=[('open_access', 'Open Access'), ('subscription', 'Subscription')], help_text='Leave blank to default from article_type on creation; editors may override.', max_length=20),
        ),
    ]
