# Generated by Django 5.2.17 on 2026-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Hero/thumbnail image shown on the homepage, listing cards, and related-article links.', null=True, upload_to='articles/images/'),
        ),
    ]
