# Generated by Django 5.2.17 on 2026-08-11 08:20

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Hero/thumbnail image shown on the homepage, listing cards, and related-article links. JPG or PNG, up to 10 MB.', null=True, upload_to='articles/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size]),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF only, up to 100 MB.', null=True, upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), articles.validators.validate_article_pdf_size]),
        ),
    ]
