# Generated by Django 5.2.17 on 2026-08-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_featured_image_alter_article_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin to the top of listings and the homepage, ahead of publication date. If more than one article is pinned, the most recently published pinned one leads.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='acceptance_date',
            field=models.DateField(blank=True, help_text='Recorded manually from OJS, if applicable — this platform has no OJS integration.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Auto-set to today when status is changed to Published, unless you set it yourself (e.g. to backdate an article or schedule a specific date).', null=True),
        ),
    ]
