# Generated by Django 5.2.17 on 2026-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_is_pinned_alter_article_acceptance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='acceptance_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
