# Generated by Django 5.2.17 on 2026-08-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_acceptance_date_and_more'),
        ('issues', '0003_issue_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Optional story trail / collection this article belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issues.issue', verbose_name='collection'),
        ),
    ]
