# Generated by Django 5.2.17 on 2026-08-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_issue'),
        ('issues', '0004_alter_issue_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Optional story trail / issue this article belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issues.issue'),
        ),
    ]
