# Generated by Django 5.2.17 on 2026-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time price, required only when access type is Pay-per-article.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='access_type',
            field=models.CharField(choices=[('open_access', 'Free'), ('subscription', 'Subscription'), ('pay_per_article', 'Pay-per-article (special)')], default='open_access', help_text='Free, subscriber-only, or a one-time-purchase "special" article.', max_length=20),
        ),
    ]
