# Generated by Django 5.2.17 on 2026-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_price_alter_article_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='homepage_section',
            field=models.CharField(blank=True, choices=[('hero', 'Hero (top story)'), ('latest_news', 'Latest News'), ('opinion', 'Opinion & Editorial'), ('research', 'Research Highlights')], help_text='Feature this article in a specific homepage section, regardless of its article type. Leave blank to let that section auto-fill from recent articles of the matching type instead — see articles/views.py HomeView.', max_length=20),
        ),
    ]
