# Generated by Django 5.2.17 on 2026-08-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_homepage_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key, used only to de-duplicate repeat views within a short window — no IP/fingerprinting.', max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='articles_ar_article_adae08_idx')],
            },
        ),
    ]
