# Generated by Django 5.2.17 on 2026-08-26 11:49
#
# Deliberately does NOT remove the old `keywords` CharField yet, even though
# it's gone from the model as of this commit — makemigrations wanted to
# combine "add keyword_tags" and "remove keywords" into one migration, which
# would drop the column (and its data) before 0021's data migration has a
# chance to copy it into real Keyword rows. `keywords` is removed for real
# in 0022, after 0021 has run. See articles/models.py's Keyword docstring.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_sync_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.keyword'),
        ),
    ]
