# Generated by Django 5.2.17 on 2026-09-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_drop_keywords_column'),
        ('sections', '0002_seed_primary_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional subject-taxonomy placement (see the sections app) — independent of article_type (format) and keyword_tags (free tags). Drives the public primary-nav landing pages, not the homepage curation slots above.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sections.section'),
        ),
    ]
