# Generated by Django 5.2.17 on 2026-09-02 18:19

import ajna_health_lens.validators
import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF only, up to 100 MB.', null=True, upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), articles.validators.validate_article_pdf_size, ajna_health_lens.validators.validate_document_content]),
        ),
    ]
