# Generated by Django 5.2.17 on 2026-09-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_article_pdf_file'),
        ('issues', '0004_alter_issue_publication_date'),
        ('sections', '0002_seed_primary_nav'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
    ]
