# Generated by Django 5.2.17 on 2026-09-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_keywordfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=20)),
                ('placement', models.CharField(blank=True, choices=[('header', 'Article header'), ('footer', 'Article footer')], max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, help_text='The article page the keyword was shown/clicked on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_events', to='articles.article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='articles.keyword')),
            ],
            options={
                'indexes': [models.Index(fields=['keyword', 'event_type', 'occurred_at'], name='articles_ke_keyword_db84e8_idx'), models.Index(fields=['event_type', 'occurred_at'], name='articles_ke_event_t_28be7c_idx')],
            },
        ),
    ]
