# Generated by Django 5.2.17 on 2026-09-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_keywordevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, help_text='Hand-picked related reading. Leave empty to let the site suggest articles by text similarity.', related_name='related_from', to='articles.article'),
        ),
    ]
