# Generated by Django 5.2.17 on 2026-09-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_article_related_articles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='affiliation',
            field=models.CharField(blank=True, help_text="Shown under the byline for name-only authors (linked accounts use their profile's affiliation).", max_length=255),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='name',
            field=models.CharField(blank=True, help_text='Byline name for an author without an account. Ignored when an account is linked.', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, help_text='Optional standfirst/summary shown under the headline and in listings. Short news pieces can leave it empty — listings then fall back to an excerpt of the body (open-access articles only; see Article.summary).'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked site account. Leave empty to credit a name without an account.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='articleauthor',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('name', ''), _negated=True), _connector='OR'), name='articleauthor_user_or_name'),
        ),
    ]
