# Generated by Django 5.2.17 on 2026-09-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_bylines_use_author_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('original_research', 'Original Research'), ('review_article', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('methodology_paper', 'Methodology Paper'), ('editorial', 'Editorial'), ('news_commentary', 'News & Commentary'), ('letter_to_editor', 'Letter to Editor')], default='news_commentary', max_length=30),
        ),
    ]
