# Generated by Django 5.2.17 on 2026-09-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_article_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
    ]
