# Generated by Django 5.2.17 on 2026-09-28 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_publish_scheduled_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='What the image shows, for screen readers and search engines. Falls back to the headline.', max_length=250, verbose_name='Image description (alt text)'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_caption',
            field=models.CharField(blank=True, help_text='Shown under the image on the article page.', max_length=300, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_credit',
            field=models.CharField(blank=True, help_text='Photographer or source, e.g. "Ram Shrestha / Ajna Health Lens".', max_length=150, verbose_name='Credit'),
        ),
        migrations.CreateModel(
            name='ArticleCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('correction', 'Correction'), ('clarification', 'Clarification'), ('update', 'Update')], default='correction', max_length=20)),
                ('note', models.TextField(help_text='What changed and why, in a sentence or two. Shown to readers.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='articles.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
