# Generated by Django 5.2.17 on 2026-09-28 06:16

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_initial_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='breaking_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='The snippet under the headline in search results and share cards. ~150 characters.', max_length=160, verbose_name='Search description'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Shown in Google results and browser tabs. Up to ~60 characters reads best.', max_length=70, verbose_name='Search headline'),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Image for Facebook/X/WhatsApp previews (1200×630 works best). Falls back to the featured image.', null=True, upload_to='articles/social/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size], verbose_name='Share image'),
        ),
    ]
