# Generated by Django 5.2.17 on 2026-09-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_seo_overrides_and_breaking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('publish_article', 'Can publish, schedule and change live articles')]},
        ),
    ]
