# Generated by Django 5.2.17 on 2026-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_publish_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerevision',
            name='bylines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
