# Generated by Django 5.2.17 on 2026-10-01 08:11

import articles.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0044_private_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste the YouTube link. The player appears at the top of the story.', max_length=300, validators=[articles.video.validate_youtube_url], verbose_name='Video (YouTube link)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('original_research', 'Original Research'), ('review_article', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('methodology_paper', 'Methodology Paper'), ('editorial', 'Editorial'), ('news_commentary', 'News & Commentary'), ('letter_to_editor', 'Letter to Editor'), ('video', 'Video')], default='news_commentary', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='homepage_section',
            field=models.CharField(blank=True, choices=[('hero', 'Hero (top story)'), ('latest_news', 'Latest News'), ('opinion', 'Opinion & Editorial'), ('research', 'Research Highlights'), ('videos', 'Videos')], help_text='Feature this article in a specific homepage section, regardless of its article type. Leave blank to let that section auto-fill from recent articles of the matching type instead — see articles/views.py HomeView.', max_length=20),
        ),
    ]
