# Generated by Django 5.2.17 on 2026-10-05 23:01

import html

from django.db import migrations, models
from django.utils.html import strip_tags

DIGITS = str.maketrans('०१२३४५६७८९', '0123456789')


def backfill(apps, schema_editor):
    """Same text as articles/search.py build_search_text, on historical models."""
    Article = apps.get_model('articles', 'Article')
    ArticleAuthor = apps.get_model('articles', 'ArticleAuthor')
    for article in Article.objects.select_related('section').prefetch_related('keyword_tags'):
        parts = [article.title, article.abstract or '', article.html_content or '']
        parts += [keyword.name for keyword in article.keyword_tags.all()]
        parts += list(ArticleAuthor.objects.filter(article=article).values_list('author__name', flat=True))
        if article.section_id:
            parts += [getattr(article.section, 'name_en', '') or article.section.name, getattr(article.section, 'name_ne', '') or '']
        text = ' '.join(html.unescape(strip_tags(' '.join(p for p in parts if p))).translate(DIGITS).split())
        Article.objects.filter(pk=article.pk).update(search_text=text)


# ngram parser: matches Devanagari, short terms and partial words. Stopwords
# must be off while the index is built — with the default list the ngram
# parser drops every 2-letter chunk containing "a" or "i" (so "malaria"
# would never match). The setting is stored with the index.
FORWARD_SQL = [
    'SET SESSION innodb_ft_enable_stopword=OFF',
    'ALTER TABLE articles_article DROP INDEX articles_article_fulltext',
    'ALTER TABLE articles_article ADD FULLTEXT INDEX articles_article_search_ngram (search_text) WITH PARSER ngram',
    'ALTER TABLE articles_article ADD FULLTEXT INDEX articles_article_title_ngram (title) WITH PARSER ngram',
    'SET SESSION innodb_ft_enable_stopword=ON',
]
REVERSE_SQL = [
    'ALTER TABLE articles_article DROP INDEX articles_article_search_ngram',
    'ALTER TABLE articles_article DROP INDEX articles_article_title_ngram',
    'ALTER TABLE articles_article ADD FULLTEXT INDEX articles_article_fulltext (title, abstract)',
]


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
