# Generated by Django 5.2.17 on 2026-10-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_search_text_word_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
    ]
