# Generated by Django 5.2.17 on 2026-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0048_keyword_unicode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to make it from the headline (e.g. "dengue-cases-rise-kathmandu").', max_length=500, unique=True),
        ),
    ]
