# Generated by Django 5.2.17 on 2026-10-07 05:51

import articles.validators
import django.core.validators
from django.db import migrations, models


def record_dimensions(apps, schema_editor):
    """Width/height of every existing featured image, so "Auto" can tell a
    square diagram from a wide photo. A missing or unreadable file is skipped."""
    from django.core.files.storage import default_storage
    from PIL import Image

    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.exclude(featured_image='').exclude(featured_image__isnull=True).only('pk', 'featured_image'):
        try:
            with default_storage.open(article.featured_image.name) as handle:
                width, height = Image.open(handle).size
        except Exception:  # noqa: BLE001 — a missing file must not stop the migration
            continue
        Article.objects.filter(pk=article.pk).update(featured_image_width=width, featured_image_height=height)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0049_slug_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_fit',
            field=models.CharField(choices=[('auto', 'Auto — whole image if it’s square or tall (diagrams), otherwise fill'), ('cover', 'Fill the space (crop the edges)'), ('contain', 'Show the whole image')], default='auto', help_text='The banner and cards are wide. A photo can be cropped to fill them; a diagram, chart or poster should be shown whole.', max_length=10, verbose_name='How to show it'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_focus_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Focal point across, 0–100 (%).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_focus_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Focal point down, 0–100 (%).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, height_field='featured_image_height', help_text='Hero/thumbnail image shown on the homepage, listing cards, and related-article links. JPG or PNG, up to 10 MB. Best: a wide photo, 1600×900 or larger.', null=True, upload_to='articles/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size], width_field='featured_image_width'),
        ),
        migrations.RunPython(record_dimensions, migrations.RunPython.noop),
    ]
