# Generated by Django 5.2.17 on 2026-10-07 06:12

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_featured_image_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Hero/thumbnail image shown on the homepage, listing cards, and related-article links. JPG or PNG, up to 10 MB. Best: a wide photo, 1600×900 or larger.', null=True, upload_to='articles/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size]),
        ),
    ]
