# Generated by Django 5.2.17 on 2026-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_rebuild_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='What the image shows, for screen readers and search engines. Filled from the slug when left empty.', max_length=250, verbose_name='Image description (alt text)'),
        ),
    ]
