# Generated by Django 5.2.17 on 2026-08-11 08:20

import django.core.validators
import issues.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='JPG or PNG, up to 10 MB.', null=True, upload_to='covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), issues.validators.validate_cover_image_size]),
        ),
    ]
