# Generated by Django 5.2.17 on 2026-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Optional — shown on the issue page if set.', null=True),
        ),
    ]
