# Generated by Django 5.2.17 on 2026-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role_title', models.CharField(help_text='e.g. "Editor-in-Chief", "Associate Editor, Cardiology".', max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='editorial_board/')),
                ('order', models.IntegerField(default=0, help_text='Display order on the public page.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members are hidden from the public page but not deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
