# Generated by Django 5.2.17 on 2026-08-11 08:20

import django.core.validators
import editorial_board.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardmember',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG or PNG, up to 5 MB.', null=True, upload_to='editorial_board/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), editorial_board.validators.validate_photo_size]),
        ),
    ]
