# Generated by Django 5.2.17 on 2026-08-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_board', '0002_alter_editorialboardmember_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboardmember',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Optional — link to this person's site account if they also have one, to cross-link their board bio with their author byline page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
