# Generated by Django 5.2.17 on 2026-08-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='task_id',
            field=models.CharField(blank=True, help_text='django_q Task id for the current/most recent send attempt — lets the editorial list distinguish "still sending" from "the background task failed".', max_length=32),
        ),
    ]
