# Generated by Django 5.2.17 on 2026-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterissue_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='audience',
            field=models.CharField(choices=[('all', 'All confirmed subscribers'), ('premium', 'Premium subscribers only')], default='all', help_text='Premium subscribers only reaches confirmed subscribers whose account has an active plan granting the premium-newsletter perk (see billing.SubscriptionPlan.grants_premium_newsletter) — see newsletter.recipients.confirmed_recipients for exactly who that is.', max_length=10),
        ),
    ]
