# Generated by Django 5.2.17 on 2026-10-05 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terms', 'Terms of use'), ('privacy', 'Privacy policy'), ('refund-policy', 'Refund policy')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ne', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ne', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Untick to take the page down. Unpublished pages are 404 to readers and not linked.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
