# Generated by Django 5.2.17 on 2026-08-20 18:59

import ads.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('zone', models.CharField(choices=[('homepage', 'Homepage'), ('article_sidebar', 'Article Page — Sidebar')], max_length=30)),
                ('image', models.ImageField(help_text='JPG or PNG, up to 5 MB.', upload_to='ads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), ads.validators.validate_ad_image_size])),
                ('link_url', models.URLField(help_text="Where a click sends the reader — the sponsor's page, not this site.")),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank to run indefinitely.', null=True)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
