# Generated by Django 5.2.17 on 2026-08-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ad_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ads.adslot')),
            ],
            options={
                'indexes': [models.Index(fields=['ad_slot', 'event_type', 'occurred_at'], name='ads_adevent_ad_slot_2002b6_idx')],
            },
        ),
    ]
