# Generated by Django 5.2.17 on 2026-08-24 06:19

import ads.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='image',
            field=models.ImageField(help_text='JPG or PNG, up to 5 MB. Must exactly match the pixel dimensions required by the selected zone — see the size reference on this form.', upload_to='ads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), ads.validators.validate_ad_image_size]),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='zone',
            field=models.CharField(choices=[('header_leaderboard', 'Site Header — Leaderboard (728×90)'), ('mobile_anchor', 'Mobile Anchor Banner (320×50)'), ('mobile_large_banner', 'Mobile — Large Banner (320×100)'), ('homepage_rectangle', 'Homepage Feed — Medium Rectangle (300×250)'), ('homepage_half_page', 'Homepage — Half Page (300×600)'), ('article_in_content', 'In-Article — Large Rectangle (336×280)'), ('article_sidebar', 'Article Sidebar — Medium Rectangle (300×250)'), ('article_skyscraper', 'Article Sidebar — Wide Skyscraper (160×600)')], max_length=30),
        ),
    ]
