# Generated by Django 5.2.17 on 2026-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_homepage_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='zone',
            field=models.CharField(choices=[('header_leaderboard', 'Site Header — Leaderboard (728×90)'), ('mobile_anchor', 'Mobile Anchor Banner (320×50)'), ('mobile_large_banner', 'Mobile — Large Banner (320×100)'), ('homepage_rectangle', 'Homepage Feed — Medium Rectangle 1 (300×250)'), ('homepage_rectangle_2', 'Homepage Feed — Medium Rectangle 2 (300×250)'), ('homepage_rectangle_3', 'Homepage Feed — Medium Rectangle 3 (300×250)'), ('homepage_leaderboard', 'Homepage — Leaderboard (728×90)'), ('article_in_content', 'In-Article — Large Rectangle (336×280)'), ('article_sidebar', 'Article Sidebar — Medium Rectangle (300×250)'), ('article_sidebar_half_page', 'Article Sidebar — Half Page (300×600)')], max_length=30),
        ),
    ]
