# Generated by Django 5.2.17 on 2026-08-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_adslot_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_placeholder_when_empty', models.BooleanField(default=False, help_text='When a zone has no active ad sold for it, show an "Advertise Here" placeholder box instead of hiding the space entirely. Never shown to a subscriber with ad-free reading, regardless of this setting — see ads/services.py:is_ad_free_reader.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad settings',
                'verbose_name_plural': 'Ad settings',
            },
        ),
    ]
