# Generated by Django 5.2.17 on 2026-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_adsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsettings',
            name='placeholder_zones',
            field=models.JSONField(blank=True, default=list, help_text='Zones where, when there is no active ad sold for it, an "Advertise Here" placeholder box is shown instead of hiding the space entirely — per zone, since a chronically unsold zone and a reliably-sold one don\'t need the same treatment. Never shown to a subscriber with ad-free reading regardless — see ads/services.py:is_ad_free_reader.'),
        ),
    ]
