# Generated by Django 5.2.17 on 2026-08-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='manuscripts/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word')], max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('article_type', models.CharField(choices=[('original_research', 'Original Research'), ('review_article', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('methodology_paper', 'Methodology Paper'), ('editorial', 'Editorial'), ('news_commentary', 'News & Commentary'), ('letter_to_editor', 'Letter to Editor')], max_length=30)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_screening', 'Under Screening'), ('under_review', 'Under Review'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_production', 'In Production'), ('published', 'Published')], default='submitted', max_length=30)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('screening_notes', models.TextField(blank=True, null=True)),
                ('plagiarism_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('decision', models.CharField(blank=True, max_length=30, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('revision_round', models.IntegerField(default=0)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('suggested_reviewers', models.TextField(blank=True, null=True)),
                ('conflict_of_interest', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
