# Generated by Django 5.2.17 on 2026-08-10 16:50

import django.core.validators
import submissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file',
            field=models.FileField(help_text='PDF, DOC, or DOCX, up to 50 MB.', upload_to='manuscripts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), submissions.validators.validate_manuscript_file_size]),
        ),
    ]
