# Generated by Django 5.2.17 on 2026-09-02 18:19

import ajna_health_lens.validators
import django.core.validators
import submissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_manuscriptfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptfile',
            name='file',
            field=models.FileField(help_text='PDF, DOC, or DOCX, up to 50 MB.', upload_to='manuscripts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), submissions.validators.validate_manuscript_file_size, ajna_health_lens.validators.validate_document_content]),
        ),
    ]
