# Generated by Django 5.2.17 on 2026-08-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ne', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in the navigation.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sections are hidden from the public nav but not deleted.')),
                ('link_url_name', models.CharField(blank=True, help_text='Set only on a top-level entry that should link straight to an existing feature\'s own page (e.g. "training:course_list") instead of a Section landing page — lets a distinct site feature (Training, Issues) sit in the same orderable nav list as a real content section. Leave blank for a normal content section.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for a top-level nav entry. Only two levels are supported — a sub-section cannot itself have children.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sections.section')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
