# Generated by Django 5.2.17 on 2026-10-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_custom', '0001_analytics_retention_schedule'),
        ('articles', '0045_article_video'),
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_summary', models.CharField(max_length=300)),
                ('reason', models.CharField(choices=[('error', 'A factual error that needs correcting'), ('misinformation', 'Misleading or dangerous health information'), ('abuse', 'Abusive, hateful or harassing'), ('privacy', 'Shares someone’s private or health information'), ('copyright', 'Uses my copyrighted work without permission'), ('spam', 'Spam or advertising'), ('other', 'Something else')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=3000)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Action taken'), ('dismissed', 'No action needed')], db_index=True, default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, help_text='What was done — kept as the record of this notice.')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='articles.article')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='django_comments_xtd.xtdcomment')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
