# Generated by Django 5.2.17 on 2026-08-21 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0014_articleview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(help_text='The pitch itself — what the story is and why it matters now.')),
                ('body', models.TextField(blank=True, help_text='Optional draft text, if you already have one. Not required to submit a pitch.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20)),
                ('editor_feedback', models.TextField(blank=True, help_text='Shown to the submitter — reason for the decision or requested changes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.OneToOneField(blank=True, help_text='Set when accepted and promoted into a real Article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pitch', to='articles.article')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
