# Generated by Django 5.2.17 on 2026-08-24 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storypitch',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Only used for an anonymous (not logged in) pitch — how to follow up with them.', max_length=254),
        ),
        migrations.AddField(
            model_name='storypitch',
            name='submitter_name',
            field=models.CharField(blank=True, help_text='Only used for an anonymous (not logged in) pitch.', max_length=255),
        ),
        migrations.AlterField(
            model_name='storypitch',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_pitches', to=settings.AUTH_USER_MODEL),
        ),
    ]
