# Generated by Django 5.2.17 on 2026-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
