# Generated by Django 5.2.17 on 2026-09-27 10:57

import articles.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_enrollment_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='audience',
            field=models.TextField(blank=True, help_text='One line per group, e.g. "Early-career researchers".', verbose_name='Who this course is for'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='category',
            field=models.CharField(blank=True, help_text='Topic used to group and filter courses, e.g. "Research Methods". Reuse the same spelling across courses.', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Landscape image (about 1200×675). JPG or PNG.', null=True, upload_to='training/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size]),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='effort',
            field=models.CharField(blank=True, help_text='Expected time commitment, e.g. "3–4 hours a week".', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='faqs',
            field=models.TextField(blank=True, help_text='Separate each question with a blank line. First line of each block is the question, the lines after it are the answer.', verbose_name='FAQs'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='instructor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='training/instructors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), articles.validators.validate_featured_image_size]),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='instructor_title',
            field=models.CharField(blank=True, help_text='e.g. "Associate Professor of Epidemiology, Tribhuvan University".', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight this course at the top of the training catalog.'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='One outcome per line. Shown as a checklist.', verbose_name="What you'll learn"),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All levels')], default='all_levels', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In person'), ('hybrid', 'Hybrid')], default='online', max_length=20, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='offers_certificate',
            field=models.BooleanField(default=False, help_text='Learners who complete the course receive a certificate.'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='One per line. Leave empty if there are none.'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave empty if learners can start any time.', null=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='subtitle',
            field=models.CharField(blank=True, help_text='One-line pitch shown under the title, e.g. "Go from research question to a publishable manuscript".', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='description',
            field=models.TextField(help_text='About this course — a few paragraphs.'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Free-text syllabus. Only shown when the course has no modules — prefer adding modules.', null=True),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='What this module covers.')),
                ('duration', models.CharField(blank=True, help_text='e.g. "Week 1" or "2 hours".', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingcourse')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
