# Generated by Django 5.2.17 on 2026-08-10 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='invited', max_length=20)),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='21 days from when the reviewer accepts the invitation.')),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=30, null=True)),
                ('comments_for_editor', models.TextField(blank=True, null=True)),
                ('comments_for_author', models.TextField(blank=True, null=True)),
                ('confidential_remarks', models.TextField(blank=True, null=True)),
                ('score_overall', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_originality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_methodology', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_significance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
